---

- name: Update and upgrade system
  ansible.builtin.apt:
          update_cache: yes
          upgrade: dist

- name: Install necessary packages
  ansible.builtin.apt:
          name: "{{ packages }}"
          state: present

- name: Gather facts
  ansible.builtin.setup:

- name: Print all gathered facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Print init system
  ansible.builtin.debug:
    msg: "Init system is {{ ansible_facts['ansible_service_mgr'] }}"

- name: Setup WiFi access point using specific tutorial
  ansible.builtin.include_tasks: ap_v1.yml
